# 训练配置文件

# 数据配置
data:
  data_dir: '/home/u2021201733/test/skill_path_matching/data'
  skill_graph_path: 'data/processed/skill_graph.pkl'
  dataset_args:
    max_skill_path_length: 10
    max_occupation_length: 5

# 模型配置
model:
  skill_input_dim: 128
  occupation_input_dim: 128
  hidden_dim: 384
  embedding_dim: 128
  num_gnn_layers: 3
  num_mlp_layers: 3
  dropout: 0.3
  gnn_type: 'gat'
  focal_alpha: 0.35
  focal_gamma: 2.5

# 训练配置
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0005
  weight_decay: 0.0005
  num_workers: 4
  lr_scheduler:
    type: 'CosineAnnealingLR'
    T_max: 50
    eta_min: 0.00001

# 训练器配置
trainer:
  early_stopping_patience: 15
  gradient_clipping: 1.0
  log_interval: 10
  save_best_only: true
  eval_metric: 'val_loss'
  monitor_mode: 'min'
